version: '3.8'
services:
# -------------------------------------------
  # list of the all containers
  backend:
    build: ./backend
    command: python3 manage.py run -h 0.0.0.0
    depends_on:
      - db
    ports: 
      - "5000:5000"
    # expose:
    #   - 5000
    volumes:
      - ./backend:/usr/src/app/
    env_file:
      - ./.env.dev
# -------------------------------------------
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    volumes:
      - ./frontend/src:/frontend/src
    environment:
      # for windows to update after save
      - CHOKIDAR_USEPOOLING=true
    env_file:
      - ./.env.dev
    # links:
      # - backend
# -------------------------------------------
  db:
    image: postgres:13-alpine
    volumes:
      - pg_db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=mk_user
      - POSTGRES_PASSWORD=mk_password
      - POSTGRES_DB=mk_db_dev
    ports:
      - '5432:5432'

volumes:
  pg_db:
